[package]
name = "v2socks"
version = "0.2.4"
authors = ["ylxdzsw <ylxdzsw@gmail.com>"]
edition = "2021"

[profile.release]
panic = "abort"
lto = true

[dependencies]
absurd = { git = "https://github.com/ylxdzsw/absurd" }
rust-crypto = "0.2"
rand = "0.8"
anyhow = "1.0"
